# This file is automatically generated, DO NOT EDIT
def CONVERT_eps_bat_tlm_bat1_temp_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-02 * pow(val, 1)
    return sum
def CONVERT_eps_bat_tlm_bat2_temp_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-02 * pow(val, 1)
    return sum
def CONVERT_eps_bat_temp_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-02 * pow(val, 1)
    return sum
def CONVERT_eps_int_temp_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-02 * pow(val, 1)
    return sum
def CONVERT_eps_bat_tlm_vcell_0_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-03 * pow(val, 1)
    return sum
def CONVERT_eps_bat_tlm_vcell_0_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-03 * pow(val, 1)
    return sum
def CONVERT_eps_bat_tlm_vcell_0_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-03 * pow(val, 1)
    return sum
def CONVERT_eps_bat_tlm_vcell_0_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-03 * pow(val, 1)
    return sum
def CONVERT_eps_bat_tlm_vin_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-03 * pow(val, 1)
    return sum
def CONVERT_eps_bat_tlm_vout_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-03 * pow(val, 1)
    return sum
def CONVERT_eps_bat_tlm_iin_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-03 * pow(val, 1)
    return sum
def CONVERT_eps_bat_tlm_iout_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_l0_hvbus_volt(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056640e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_l0_lvbus_volt(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056640e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_l0_1p8_volt(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056640e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_l0_2p5_volt(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056640e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_l0_det_temp(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056640e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_l0_1p0_volt(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056640e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_l0_flash_pwr(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056640e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_l0_box_temp(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056640e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_general_inertia0_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_general_inertia1_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_general_inertia2_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_general_inertia0_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_general_inertia1_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_general_inertia2_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_general_inertia0_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_general_inertia1_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_general_inertia2_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_time_tai_seconds(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_time_now(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_q_ecef_wrt_eci_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_q_ecef_wrt_eci_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_q_ecef_wrt_eci_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_q_ecef_wrt_eci_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_position_wrt_eci_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_position_wrt_eci_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_position_wrt_eci_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_position_wrt_ecef_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_position_wrt_ecef_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_position_wrt_ecef_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_velocity_wrt_eci_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_velocity_wrt_eci_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_velocity_wrt_eci_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_velocity_wrt_ecef_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_velocity_wrt_ecef_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_velocity_wrt_ecef_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_nadir_vector_body_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_nadir_vector_body_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_nadir_vector_body_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_gd_nadir_vector_body_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_gd_nadir_vector_body_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_gd_nadir_vector_body_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_modeled_sun_vector_body_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_modeled_sun_vector_body_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_modeled_sun_vector_body_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_moon_vector_body_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_moon_vector_body_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_moon_vector_body_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_mag_model_vector_eci_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_mag_model_vector_eci_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_mag_model_vector_eci_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_mag_model_vector_body_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_mag_model_vector_body_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_mag_model_vector_body_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_sun_position_wrt_eci_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_sun_position_wrt_eci_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_sun_position_wrt_eci_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_moon_position_wrt_eci_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_moon_position_wrt_eci_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_moon_position_wrt_eci_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_latitude(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_longitude(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_altitude(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_refs_beta_angle(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_att_det_q_body_wrt_eci_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_att_det_q_body_wrt_eci_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_att_det_q_body_wrt_eci_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_att_det_q_body_wrt_eci_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_att_det_residual_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_att_det_residual_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_att_det_residual_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_att_det_body_rate_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_att_det_body_rate_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_att_det_body_rate_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_att_det_gyro_bias_est_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-07 * pow(val, 1)
    return sum
def CONVERT_adcs_att_det_gyro_bias_est_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-07 * pow(val, 1)
    return sum
def CONVERT_adcs_att_det_gyro_bias_est_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-07 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_cmd_q_body_wrt_eci_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_cmd_q_body_wrt_eci_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_cmd_q_body_wrt_eci_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_cmd_q_body_wrt_eci_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_cmd_target_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_cmd_target_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_cmd_target_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_pri_cmd_vec_body_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.076923e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_pri_cmd_vec_body_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.076923e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_pri_cmd_vec_body_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.076923e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_sec_cmd_vec_body_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.076923e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_sec_cmd_vec_body_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.076923e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_sec_cmd_vec_body_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.076923e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_q_target_wrt_ref0_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.076923e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_q_target_wrt_ref0_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.076923e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_q_target_wrt_ref0_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.076923e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_q_target_wrt_ref0_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.076923e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_cmd_body_rate_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_cmd_body_rate_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_cmd_body_rate_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_cmd_body_accel_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_cmd_body_accel_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_cmd_body_accel_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_commanded_sun_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_commanded_sun_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_commanded_sun_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_att_cmd_rotisserie_rate(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_theta_err_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_theta_err_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_theta_err_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_theta_err_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_drag_est_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-02 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_drag_est_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-02 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_drag_est_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-02 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_drag_est_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-02 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_obs_angle_residual_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.500000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_obs_angle_residual_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.500000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_obs_angle_residual_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.500000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_obs_angle_residual_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.500000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_filtered_speed_rpm_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_filtered_speed_rpm_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_filtered_speed_rpm_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_filtered_speed_rpm_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_speed_cmd_rpm_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-01 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_speed_cmd_rpm_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-01 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_speed_cmd_rpm_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-01 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_speed_cmd_rpm_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e-01 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_torque_command_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-08 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_torque_command_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-08 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_torque_command_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-08 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_torque_command_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-08 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_meas_wheel_current_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_meas_wheel_current_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_meas_wheel_current_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_rw_drive_meas_wheel_current_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_attitude_st_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.882812e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_attitude_st_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.882812e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_attitude_st_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.882812e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_attitude_st_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.882812e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_rate_est_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.500000e-06 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_rate_est_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.500000e-06 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_rate_est_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.500000e-06 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_right_asc(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.500000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_declination(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.500000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_roll(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.500000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_att_covariance_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.470588e-14 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_att_covariance_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.470588e-14 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_att_covariance_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.470588e-14 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_att_covariance_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.470588e-14 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_att_covariance_4(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.470588e-14 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_att_covariance_5(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.470588e-14 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_peak_noise_all_trk_blks(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_peak_bckgnd_all_trk_blks(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_median_noise_all_trk_blks(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_median_bckgnd_all_trk_blks(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_position_error_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_position_error_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_position_error_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_rate_error_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_rate_error_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_rate_error_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_integral_error_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_integral_error_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_integral_error_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_eigen_error(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_max_rate_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_max_rate_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_max_rate_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_max_accel_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_max_accel_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_max_accel_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_feedback_ctrl_torq_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-07 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_feedback_ctrl_torq_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-07 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_feedback_ctrl_torq_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-07 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_control_torque_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_control_torque_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_control_torque_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_att_ctrl_sun_point_angle_error(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_momentum_total_momentum_mag(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_momentum_momentum_vector_body_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_momentum_momentum_vector_body_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_momentum_momentum_vector_body_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_momentum_wheel_momentum_body_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_momentum_wheel_momentum_body_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_momentum_wheel_momentum_body_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_momentum_bus_momentum_body_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_momentum_bus_momentum_body_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_momentum_bus_momentum_body_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_momentum_cmd_momentum_inertial_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-06 * pow(val, 1)
    return sum
def CONVERT_adcs_momentum_cmd_momentum_inertial_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-06 * pow(val, 1)
    return sum
def CONVERT_adcs_momentum_cmd_momentum_inertial_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-06 * pow(val, 1)
    return sum
def CONVERT_adcs_momentum_cycle_avg_magnet_torque_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-08 * pow(val, 1)
    return sum
def CONVERT_adcs_momentum_cycle_avg_magnet_torque_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-08 * pow(val, 1)
    return sum
def CONVERT_adcs_momentum_cycle_avg_magnet_torque_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-08 * pow(val, 1)
    return sum
def CONVERT_adcs_css_sun_vector_body_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_css_sun_vector_body_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_css_sun_vector_body_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_mag_mag_vector_body_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-08 * pow(val, 1)
    return sum
def CONVERT_adcs_mag_mag_vector_body_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-08 * pow(val, 1)
    return sum
def CONVERT_adcs_mag_mag_vector_body_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-08 * pow(val, 1)
    return sum
def CONVERT_adcs_imu_imu_avg_vector_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_imu_imu_avg_vector_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_imu_imu_avg_vector_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_imu_avg_body_accel_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_imu_avg_body_accel_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_imu_avg_body_accel_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_analogs_voltage_2p_5(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.500000e-02 * pow(val, 1)
    return sum
def CONVERT_adcs_analogs_voltage_1p_8(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.500000e-02 * pow(val, 1)
    return sum
def CONVERT_adcs_analogs_voltage_1p_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.500000e-02 * pow(val, 1)
    return sum
def CONVERT_adcs_analogs_det_temp(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.000000e-01 * pow(val, 1)
    return sum
def CONVERT_adcs_analogs_ext_temp(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_analogs_imu_temp(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_analogs_motor_1temp(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_analogs_motor_2temp(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_analogs_motor_3temp(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_analogs_motor_4temp(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_analogs_digital_bus_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.250000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_analogs_motor_bus_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.250000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_analogs_rod_bus_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.250000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_attitude_st_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.882812e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_attitude_st_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.882812e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_attitude_st_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.882812e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_attitude_st_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.882812e-10 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_rate_est_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.500000e-06 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_rate_est_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.500000e-06 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_rate_est_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.500000e-06 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_right_asc(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.500000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_declination(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.500000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_roll(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.500000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_att_covariance_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.470588e-14 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_att_covariance_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.470588e-14 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_att_covariance_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.470588e-14 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_att_covariance_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.470588e-14 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_att_covariance_4(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.470588e-14 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_att_covariance_5(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.470588e-14 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_peak_noise_all_trk_blks(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_peak_bckgnd_all_trk_blks(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_median_noise_all_trk_blks(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_2_median_bckgnd_all_trk_blks(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 4.000000e+00 * pow(val, 1)
    return sum
def CONVERT_adcs_gps_gps_position_ecef_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_gps_gps_position_ecef_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_gps_gps_position_ecef_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_gps_gps_velocity_ecef_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_gps_gps_velocity_ecef_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_gps_gps_velocity_ecef_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_gps_msg_gps_temp_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.857143e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_gps_msg_gps_temp_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.857143e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_gps_msg_ant_current(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.525902e-05 * pow(val, 1)
    return sum
def CONVERT_adcs_gps_msg_ant_voltage(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_gps_msg_gps_voltage_supply(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-04 * pow(val, 1)
    return sum
def CONVERT_adcs_gps_msg_gps_voltage_3p_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.333333e-02 * pow(val, 1)
    return sum
def CONVERT_adcs_gps_msg_gps_voltage_1p_8(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-02 * pow(val, 1)
    return sum
def CONVERT_adcs_gps_msg_gps_voltage_1p_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-02 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_q_tracker_wrt_body_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_q_tracker_wrt_body_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_q_tracker_wrt_body_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_q_tracker_wrt_body_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_q_tracker_wrt_body_4(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_q_tracker_wrt_body_5(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_q_tracker_wrt_body_6(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_q_tracker_wrt_body_7(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_q_tracker_wrt_body_est_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_q_tracker_wrt_body_est_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_q_tracker_wrt_body_est_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_q_tracker_wrt_body_est_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_q_tracker_wrt_body_est_4(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_q_tracker_wrt_body_est_5(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_q_tracker_wrt_body_est_6(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_q_tracker_wrt_body_est_7(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_tracker_align_used_res_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_tracker_align_used_res_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_tracker_align_used_res_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_tracker_align_est_res_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_tracker_align_est_res_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_cal_tracker_align_est_res_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_ctrl_q_body_wrt_eci_0(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_ctrl_q_body_wrt_eci_1(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_ctrl_q_body_wrt_eci_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_ctrl_q_body_wrt_eci_3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_ctrl_q_body_wrt_eci_4(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_ctrl_q_body_wrt_eci_5(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_ctrl_q_body_wrt_eci_6(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_tracker_ctrl_q_body_wrt_eci_7(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.000000e-09 * pow(val, 1)
    return sum
def CONVERT_adcs_ext_tracker_2_voltage_2p_5(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.500000e-02 * pow(val, 1)
    return sum
def CONVERT_adcs_ext_tracker_2_voltage_1p_8(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.500000e-02 * pow(val, 1)
    return sum
def CONVERT_adcs_ext_tracker_2_voltage_1p_2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.500000e-02 * pow(val, 1)
    return sum
def CONVERT_adcs_ext_tracker_2_det_temp(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.000000e-01 * pow(val, 1)
    return sum
def CONVERT_adcs_ext_tracker_2_digital_bus_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.250000e-03 * pow(val, 1)
    return sum
def CONVERT_adcs_ext_tracker_2_ext_lv_bus_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.250000e-03 * pow(val, 1)
    return sum
def CONVERT_ana_bus_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.862300e-03 * pow(val, 1)
    return sum
def CONVERT_ana_3p3_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.611300e-03 * pow(val, 1)
    return sum
def CONVERT_ana_2p5_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056600e-04 * pow(val, 1)
    return sum
def CONVERT_ana_1p8_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056600e-04 * pow(val, 1)
    return sum
def CONVERT_ana_1p0_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056600e-04 * pow(val, 1)
    return sum
def CONVERT_ana_3p3_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056600e-05 * pow(val, 1)
    return sum
def CONVERT_ana_1p8_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056600e-05 * pow(val, 1)
    return sum
def CONVERT_ana_1p0_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056600e-05 * pow(val, 1)
    return sum
def CONVERT_ana_cdh_temp(val):
    sum = 0
    sum += 1.255500e+02 * pow(val, 0)
    sum += -1.362200e-01 * pow(val, 1)
    sum += 9.861100e-05 * pow(val, 2)
    sum += -4.417600e-08 * pow(val, 3)
    sum += 1.012500e-11 * pow(val, 4)
    sum += -9.390500e-16 * pow(val, 5)
    return sum
def CONVERT_ana_cdh_3p3_ref(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.611300e-03 * pow(val, 1)
    return sum
def CONVERT_ana_inst1_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.963900e-03 * pow(val, 1)
    return sum
def CONVERT_ana_inst1_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.220700e-03 * pow(val, 1)
    return sum
def CONVERT_ana_inst2_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.963900e-03 * pow(val, 1)
    return sum
def CONVERT_ana_inst2_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.220700e-03 * pow(val, 1)
    return sum
def CONVERT_ana_inst3_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.963900e-03 * pow(val, 1)
    return sum
def CONVERT_ana_inst3_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.220700e-03 * pow(val, 1)
    return sum
def CONVERT_ana_inst_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.963900e-03 * pow(val, 1)
    return sum
def CONVERT_ana_inst_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.220700e-03 * pow(val, 1)
    return sum
def CONVERT_ana_interface1_therm(val):
    sum = 0
    sum += 1.255500e+02 * pow(val, 0)
    sum += -1.362200e-01 * pow(val, 1)
    sum += 9.861100e-05 * pow(val, 2)
    sum += -4.417600e-08 * pow(val, 3)
    sum += 1.012500e-11 * pow(val, 4)
    sum += -9.390500e-16 * pow(val, 5)
    return sum
def CONVERT_ana_interface2_therm(val):
    sum = 0
    sum += 1.255500e+02 * pow(val, 0)
    sum += -1.362200e-01 * pow(val, 1)
    sum += 9.861100e-05 * pow(val, 2)
    sum += -4.417600e-08 * pow(val, 3)
    sum += 1.012500e-11 * pow(val, 4)
    sum += -9.390500e-16 * pow(val, 5)
    return sum
def CONVERT_ana_sa1_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 9.659200e-03 * pow(val, 1)
    return sum
def CONVERT_ana_sa1_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.014200e-03 * pow(val, 1)
    return sum
def CONVERT_ana_sa2_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 9.659200e-03 * pow(val, 1)
    return sum
def CONVERT_ana_sa2_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.014200e-03 * pow(val, 1)
    return sum
def CONVERT_ana_bat1_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.862300e-03 * pow(val, 1)
    return sum
def CONVERT_ana_bat2_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.862300e-03 * pow(val, 1)
    return sum
def CONVERT_ana_eps_temp(val):
    sum = 0
    sum += 1.255500e+02 * pow(val, 0)
    sum += -1.362200e-01 * pow(val, 1)
    sum += 9.861100e-05 * pow(val, 2)
    sum += -4.417600e-08 * pow(val, 3)
    sum += 1.012500e-11 * pow(val, 4)
    sum += -9.390500e-16 * pow(val, 5)
    return sum
def CONVERT_ana_eps_3p3_ref(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.611330e-03 * pow(val, 1)
    return sum
def CONVERT_ana_eps_bus_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.862300e-03 * pow(val, 1)
    return sum
def CONVERT_ana_eps_bus_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.220700e-03 * pow(val, 1)
    return sum
def CONVERT_ana_xact_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.862300e-03 * pow(val, 1)
    return sum
def CONVERT_ana_xact_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.014200e-03 * pow(val, 1)
    return sum
def CONVERT_ana_uhf_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.862300e-03 * pow(val, 1)
    return sum
def CONVERT_ana_uhf_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.014200e-03 * pow(val, 1)
    return sum
def CONVERT_ana_xband_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.862300e-03 * pow(val, 1)
    return sum
def CONVERT_ana_xband_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.014200e-03 * pow(val, 1)
    return sum
def CONVERT_sw_adcs_body_rt3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-09 * pow(val, 1)
    return sum
def CONVERT_sw_xband_pa_temp(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 9.765625e-04 * pow(val, 1)
    return sum
def CONVERT_sw_xband_pa_curr(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.654473e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_3p3_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.611300e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_1p8_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056600e-04 * pow(val, 1)
    return sum
def CONVERT_sw_ana_1p0_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056600e-04 * pow(val, 1)
    return sum
def CONVERT_sw_ana_3p3_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056600e-05 * pow(val, 1)
    return sum
def CONVERT_sw_ana_1p8_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056600e-05 * pow(val, 1)
    return sum
def CONVERT_sw_ana_1p0_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.056600e-05 * pow(val, 1)
    return sum
def CONVERT_sw_ana_cdh_temp(val):
    sum = 0
    sum += 1.255500e+02 * pow(val, 0)
    sum += -1.362200e-01 * pow(val, 1)
    sum += 9.861100e-05 * pow(val, 2)
    sum += -4.417600e-08 * pow(val, 3)
    sum += 1.012500e-11 * pow(val, 4)
    sum += -9.390500e-16 * pow(val, 5)
    return sum
def CONVERT_sw_ana_cdh_3p3_ref(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.611300e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_sa1_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 9.659200e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_sa1_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.014200e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_sa2_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 9.659200e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_sa2_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.014200e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_bat1_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.862300e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_eps_temp(val):
    sum = 0
    sum += 1.255500e+02 * pow(val, 0)
    sum += -1.362200e-01 * pow(val, 1)
    sum += 9.861100e-05 * pow(val, 2)
    sum += -4.417600e-08 * pow(val, 3)
    sum += 1.012500e-11 * pow(val, 4)
    sum += -9.390500e-16 * pow(val, 5)
    return sum
def CONVERT_sw_ana_eps_3p3_ref(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.611330e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_eps_bus_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.862300e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_eps_bus_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.220700e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_xact_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.862300e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_xact_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.014200e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_uhf_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.862300e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_uhf_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.014200e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_xband_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.862300e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_xband_i(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.014200e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_inst1_volt(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.963900e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_inst1_curr(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.220700e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_inst2_volt(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.963900e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_inst2_curr(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.220700e-03 * pow(val, 1)
    return sum
def CONVERT_sw_ana_ifb_therm1(val):
    sum = 0
    sum += 1.255500e+02 * pow(val, 0)
    sum += -1.362200e-01 * pow(val, 1)
    sum += 9.861100e-05 * pow(val, 2)
    sum += -4.417600e-08 * pow(val, 3)
    sum += 1.012500e-11 * pow(val, 4)
    sum += -9.390500e-16 * pow(val, 5)
    return sum
def CONVERT_sw_adcs_analogs_motor1_temp(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 5.000000e-03 * pow(val, 1)
    return sum
def CONVERT_sw_adcs_analogs_digital_bus_v(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.250000e-03 * pow(val, 1)
    return sum
def CONVERT_sw_adcs_wheel_sp3(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.000000e-03 * pow(val, 1)
    return sum
def CONVERT_sw_adcs_att_ctrl_sun_point_angle_error(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 3.000000e-03 * pow(val, 1)
    return sum
def CONVERT_sw_adcs_analogs_voltage_2p5(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.500000e-02 * pow(val, 1)
    return sum
def CONVERT_sw_adcs_analogs_voltage_1p8(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.500000e-02 * pow(val, 1)
    return sum
def CONVERT_sw_adcs_analogs_voltage_1p2(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.500000e-02 * pow(val, 1)
    return sum
def CONVERT_sw_adcs_analogs_det_temp(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 8.000000e-01 * pow(val, 1)
    return sum
def CONVERT_xband_hk_input_volts(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 7.326007e-03 * pow(val, 1)
    return sum
def CONVERT_xband_hk_input_amps(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.654473e-03 * pow(val, 1)
    return sum
def CONVERT_xband_hk_5p0va_volts(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 2.442002e-03 * pow(val, 1)
    return sum
def CONVERT_xband_hk_5p0va_amps(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.654473e-03 * pow(val, 1)
    return sum
def CONVERT_xband_hk_3p3va_volts(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.221001e-03 * pow(val, 1)
    return sum
def CONVERT_xband_hk_3p3va_amps(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.654473e-03 * pow(val, 1)
    return sum
def CONVERT_xband_hk_3p3vd_amps(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.654473e-03 * pow(val, 1)
    return sum
def CONVERT_xband_hk_3p0va_volts(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.221001e-03 * pow(val, 1)
    return sum
def CONVERT_xband_hk_3p0va_amps(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.654473e-03 * pow(val, 1)
    return sum
def CONVERT_xband_hk_1p5vd_amps(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.654473e-03 * pow(val, 1)
    return sum
def CONVERT_xband_hk_power_amp_drain_volts(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.221001e-03 * pow(val, 1)
    return sum
def CONVERT_xband_hk_power_amp_drain_amps(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.654473e-03 * pow(val, 1)
    return sum
def CONVERT_xband_hk_amp_a_amps(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.654473e-03 * pow(val, 1)
    return sum
def CONVERT_xband_hk_amp_b_amps(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.654473e-03 * pow(val, 1)
    return sum
def CONVERT_xband_hk_amp_c_amps(val):
    sum = 0
    sum += 0.000000e+00 * pow(val, 0)
    sum += 1.654473e-03 * pow(val, 1)
    return sum
