name: suncet-dev
channels:
  - conda-forge
dependencies:
  - python=3.14
  - pip
  - numpy>=2.0
  - scipy>=1.13
  - matplotlib>=3.8
  - pillow>=10.2
  - imagecodecs>=2025.3.30
  - h5netcdf>=1.3
  - duckdb>=1.4
  - pandas>=2.2
  - psutil>=5.9
  - tqdm>=4.64
  - astropy>=6.1
  - sunpy>=6.0
  - sunkit-image>=0.6
  - xarray>=2024.7
  - netcdf4>=1.7
  - bottleneck>=1.4
  - termcolor>=2.4
  - pykdtree>=1.3.13
  - pytest>=9.0
  - pytest-cov>=7.0
  - jupyter>=1.1
  - seaborn>=0.13
