name: suncet
channels:
  - conda-forge

dependencies:
  - pip >=22.1
  - python=3.10
  - pytest-cov=3.0
  - numpy=1.22
  - matplotlib=3.5
  - jupyter=1.0
  - scipy=1.8.1
  - sunkit-image >=0.5
  - astropy=5.1
  - sunpy >=4.0
  - xarray=2022.6.0
  - netCDF4=1.6.0
  - bottleneck=1.3.7
  - gnuradio=3.10.5.1
  - gnuradio-satellites=5.2.0
  - termcolor==2.4.0
  - pytest==7.1.3
  - h5netcdf==1.1.0
  - pykdtree==1.3.13
