"""Static, numbered visual explanation of the Level 4 CME method.

The figures written here are diagnostic teaching products, not additional
science products.  Science-space arrays are regenerated by the same polar and
likelihood functions used by :func:`run_known_window`; intensity stretches are
applied only while rendering and are labeled as display-only in every panel
where they occur.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
import math
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np

from .likelihood import LikelihoodResult, score_front_likelihood
from .polar import remap_image_to_polar
from .tracking import _frame_candidates

if TYPE_CHECKING:
    from matplotlib.figure import Figure

    from .pipeline import CMETrackingRun


@dataclass(frozen=True)
class CMEExplanationArtifacts:
    """Paths and representative coordinates for one method explanation."""

    frame_index: int
    frame_number: int
    representative_position_angle_deg: float
    panel_paths: tuple[Path, ...]
    overview_path: Path


_PANEL_FILENAMES = (
    "01_original_input.png",
    "02_polar_remap.png",
    "03_temporal_background.png",
    "04_base_excess_evidence.png",
    "05_running_difference_evidence.png",
    "06_leading_edge_evidence.png",
    "07_combined_score.png",
    "08_candidates_vs_retained_front.png",
    "09_representative_time_radius_path.png",
    "10_backprojected_retained_front.png",
    "11_scalar_height_reduction.png",
)


def _pyplot():
    """Import pyplot only after forcing a headless rendering backend."""

    import matplotlib

    matplotlib.use("Agg", force=True)
    import matplotlib.pyplot as pyplot

    return pyplot


def _same_array(first: np.ndarray, second: np.ndarray) -> bool:
    return bool(
        np.array_equal(
            np.asarray(first),
            np.asarray(second),
            equal_nan=True,
        )
    )


def recompute_evidence_diagnostics(run: "CMETrackingRun") -> LikelihoodResult:
    """Regenerate evidence channels without modifying the completed run.

    Cartesian FITS images are read and remapped one at a time.  Only the
    smaller polar sequence is retained long enough to apply the same
    sequence-wide robust normalizations as the science run.  Enabling
    ``retain_diagnostics`` changes only which intermediate arrays are returned;
    the recomputed score and temporal background are required to reproduce the
    stored science result bit for bit.
    """

    grid = run.polar_grid
    polar_images = np.empty(
        (run.sequence.frame_count, *grid.shape),
        dtype=np.float32,
    )
    for frame_index in range(run.sequence.frame_count):
        image = np.asarray(
            run.sequence.read_frame(frame_index).data,
            dtype=np.float32,
        )
        polar_images[frame_index] = remap_image_to_polar(image, grid)

    diagnostic_config = replace(
        run.configuration.evidence,
        retain_diagnostics=True,
    )
    diagnostics = score_front_likelihood(
        polar_images,
        grid,
        diagnostic_config,
    )
    del polar_images

    if not _same_array(diagnostics.score, run.likelihood.score):
        raise RuntimeError(
            "Diagnostic evidence recomputation did not exactly reproduce "
            "the stored Level 4 score."
        )
    if not _same_array(
        diagnostics.temporal_background,
        run.likelihood.temporal_background,
    ):
        raise RuntimeError(
            "Diagnostic evidence recomputation did not exactly reproduce "
            "the stored temporal background."
        )
    if not np.array_equal(
        diagnostics.supported_frame_mask,
        run.likelihood.supported_frame_mask,
    ):
        raise RuntimeError(
            "Diagnostic evidence recomputation did not reproduce the stored "
            "temporal support mask."
        )
    if any(
        channel is None
        for channel in (
            diagnostics.base_excess_z,
            diagnostics.running_difference_z,
            diagnostics.leading_edge_z,
        )
    ):
        raise RuntimeError("Requested diagnostic evidence channels were not retained.")
    return diagnostics


def _sequence_display_limits(
    run: "CMETrackingRun",
) -> tuple[float, float, float]:
    """Return a stable asinh stretch from streamed representative frames."""

    sample_count = min(12, run.sequence.frame_count)
    sample_indices = np.unique(
        np.linspace(0, run.sequence.frame_count - 1, sample_count)
        .round()
        .astype(int)
    )
    lows: list[float] = []
    highs: list[float] = []
    for frame_index in sample_indices:
        image = np.asarray(
            run.sequence.read_frame(int(frame_index)).data,
            dtype=np.float64,
        )
        finite = image[np.isfinite(image)]
        if finite.size:
            low, high = np.percentile(finite, (1.0, 99.7))
            lows.append(float(low))
            highs.append(float(high))
    if not lows:
        raise ValueError("Explanation input contains no finite image pixels.")
    low = float(np.median(lows))
    high = float(np.median(highs))
    if not high > low:
        high = low + max(abs(low), 1.0) * np.finfo(np.float64).eps
    linear_width = max((high - low) * 0.03, np.finfo(np.float64).eps)
    return low, high, linear_width


def _asinh_display(
    values: np.ndarray,
    *,
    low: float,
    linear_width: float,
) -> np.ndarray:
    return np.arcsinh(
        (np.asarray(values, dtype=np.float64) - low) / linear_width
    )


def _save_figure(
    pyplot,
    figure: "Figure",
    path: Path,
    *,
    dpi: int,
    title: str,
) -> None:
    figure.savefig(
        path,
        dpi=dpi,
        bbox_inches="tight",
        facecolor="white",
        metadata={
            "Title": title,
            "Creator": "SunCET Level 4 CME method explanation renderer",
        },
    )
    pyplot.close(figure)


def _add_caption(figure: "Figure", caption: str) -> None:
    figure.text(
        0.5,
        0.018,
        caption,
        ha="center",
        va="bottom",
        fontsize=9,
        color="0.25",
        wrap=True,
    )


def _polar_extent(run: "CMETrackingRun") -> tuple[float, float, float, float]:
    radius = run.polar_grid.radius_rsun
    return float(radius[0]), float(radius[-1]), 0.0, 360.0


def _render_polar_image(
    axis,
    run: "CMETrackingRun",
    values: np.ndarray,
    *,
    cmap: str,
    vmin: float,
    vmax: float,
    colorbar_label: str,
    figure: "Figure",
):
    # Work on a private colormap so invalid rectangular-FOV samples remain
    # visibly distinct from genuine zero-valued evidence.
    import matplotlib.pyplot as pyplot

    colormap = pyplot.get_cmap(cmap).copy()
    colormap.set_bad("#d9d9d9")
    artist = axis.imshow(
        values,
        origin="lower",
        aspect="auto",
        interpolation="nearest",
        extent=_polar_extent(run),
        cmap=colormap,
        vmin=vmin,
        vmax=vmax,
    )
    axis.set_xlabel(r"Projected radius ($R_\odot$)")
    axis.set_ylabel("Solar position angle (deg; north=0, east=90)")
    colorbar = figure.colorbar(artist, ax=axis, pad=0.02)
    colorbar.set_label(colorbar_label)
    return artist


def _signed_display_limit(values: np.ndarray, clip: float) -> float:
    finite = np.abs(np.asarray(values, dtype=np.float64))
    finite = finite[np.isfinite(finite)]
    if not finite.size:
        return 1.0
    percentile = float(np.percentile(finite, 99.0))
    return max(min(percentile, float(clip)), np.finfo(np.float64).eps)


def _positive_display_limit(values: np.ndarray, floor: float = 1.0) -> float:
    finite = np.asarray(values, dtype=np.float64)
    finite = finite[np.isfinite(finite)]
    if not finite.size:
        return float(floor)
    return max(float(np.percentile(finite, 99.5)), float(floor))


def _frame_candidates_for_all_angles(
    run: "CMETrackingRun",
    frame_index: int,
) -> tuple[np.ndarray, np.ndarray]:
    candidate_angles: list[float] = []
    candidate_radii: list[float] = []
    for angle_index, position_angle in enumerate(
        run.polar_grid.position_angle_deg
    ):
        candidates = _frame_candidates(
            run.likelihood.score[frame_index, angle_index],
            run.polar_grid,
            run.configuration.tracking,
        )
        for candidate in candidates:
            candidate_angles.append(float(position_angle))
            candidate_radii.append(
                float(run.polar_grid.radius_rsun[candidate.radius_index])
            )
    return (
        np.asarray(candidate_angles, dtype=np.float64),
        np.asarray(candidate_radii, dtype=np.float64),
    )


def _representative_angle_index(
    run: "CMETrackingRun",
    frame_index: int,
) -> int:
    observed = run.front.observed_mask
    support = np.count_nonzero(observed, axis=0)
    eligible = np.flatnonzero(observed[frame_index])
    if eligible.size:
        frame_radii = run.front.radius_rsun[frame_index, eligible]
        finite = np.isfinite(frame_radii)
        if np.any(finite):
            finite_eligible = eligible[finite]
            return int(finite_eligible[int(np.argmax(frame_radii[finite]))])
    if not eligible.size:
        eligible = np.flatnonzero(support > 0)

    if eligible.size:
        maximum_support = int(np.max(support[eligible]))
        eligible = eligible[support[eligible] == maximum_support]
        target = float(run.summary.position_angle_deg[frame_index])
        if math.isfinite(target):
            angles = run.polar_grid.position_angle_deg[eligible]
            circular_distance = np.abs(
                (angles - target + 180.0) % 360.0 - 180.0
            )
            return int(eligible[int(np.argmin(circular_distance))])

        median_score = np.full(eligible.size, -np.inf, dtype=np.float64)
        for offset, angle_index in enumerate(eligible):
            selected = run.front.score[:, angle_index]
            finite = selected[np.isfinite(selected)]
            if finite.size:
                median_score[offset] = float(np.median(finite))
        return int(eligible[int(np.argmax(median_score))])

    selected_score = np.asarray(
        run.likelihood.score[frame_index],
        dtype=np.float64,
    )
    finite_score = np.where(np.isfinite(selected_score), selected_score, -np.inf)
    maximum_by_angle = np.max(finite_score, axis=1)
    if np.any(np.isfinite(maximum_by_angle)):
        return int(np.argmax(maximum_by_angle))
    return 0


def _time_radius_candidates(
    run: "CMETrackingRun",
    angle_index: int,
) -> tuple[np.ndarray, np.ndarray]:
    elapsed: list[float] = []
    radius: list[float] = []
    for frame_index, frame_score in enumerate(
        run.likelihood.score[:, angle_index, :]
    ):
        for candidate in _frame_candidates(
            frame_score,
            run.polar_grid,
            run.configuration.tracking,
        ):
            elapsed.append(float(run.sequence.elapsed_seconds[frame_index]))
            radius.append(
                float(run.polar_grid.radius_rsun[candidate.radius_index])
            )
    return (
        np.asarray(elapsed, dtype=np.float64),
        np.asarray(radius, dtype=np.float64),
    )


def _backproject_front(
    run: "CMETrackingRun",
    frame_index: int,
) -> tuple[np.ndarray, np.ndarray]:
    observed = run.front.observed_mask[frame_index]
    radii = run.front.radius_px[frame_index, observed]
    angles = np.deg2rad(run.front.position_angle_deg[observed])
    geometry = run.sequence.geometry
    north_y, north_x = geometry.north_vector_yx
    east_y, east_x = geometry.east_vector_yx
    y = geometry.center_y_px + radii * (
        np.cos(angles) * north_y + np.sin(angles) * east_y
    )
    x = geometry.center_x_px + radii * (
        np.cos(angles) * north_x + np.sin(angles) * east_x
    )
    return np.asarray(x), np.asarray(y)


def _write_contact_sheet(
    pyplot,
    panel_paths: tuple[Path, ...],
    overview_path: Path,
    *,
    frame_index: int,
    frame_number: int,
    dpi: int,
) -> None:
    figure, axes = pyplot.subplots(3, 4, figsize=(20.0, 13.2))
    figure.suptitle(
        "Level 4 CME bright-front method — numbered visual walkthrough\n"
        f"representative sequence row {frame_index}, frame number {frame_number}",
        fontsize=18,
        fontweight="bold",
    )
    for axis, path in zip(axes.flat, panel_paths, strict=False):
        axis.imshow(pyplot.imread(path))
        axis.set_title(path.stem.replace("_", " "), fontsize=10)
        axis.axis("off")
    for axis in axes.flat[len(panel_paths) :]:
        axis.axis("off")
    figure.text(
        0.5,
        0.018,
        "Intensity stretches are display-only. Polar remapping, temporal "
        "background subtraction, robust z-scores, sparse-path tracking, and "
        "the scalar percentile are science-space operations.",
        ha="center",
        fontsize=10,
        color="0.25",
    )
    figure.tight_layout(rect=(0.01, 0.04, 0.99, 0.95))
    _save_figure(
        pyplot,
        figure,
        overview_path,
        dpi=dpi,
        title="Level 4 CME bright-front method overview",
    )


def write_cme_method_explanation(
    run: "CMETrackingRun",
    frame_index: int,
    output_directory: str | Path,
    *,
    dpi: int = 140,
) -> CMEExplanationArtifacts:
    """Write a numbered visual walkthrough for one representative frame.

    The caller chooses the sequence row explicitly; for a middle-frame example
    use ``run.sequence.frame_count // 2``.  The output consists of eleven
    individual PNGs plus ``00_method_overview.png``.  Existing files with those
    names are replaced, while unrelated files in the directory are untouched.
    """

    if isinstance(frame_index, (bool, np.bool_)) or not isinstance(
        frame_index, (int, np.integer)
    ):
        raise TypeError("frame_index must be an integer sequence row.")
    frame_index = int(frame_index)
    if not 0 <= frame_index < run.sequence.frame_count:
        raise IndexError(
            f"frame_index {frame_index} is outside the available range "
            f"0..{run.sequence.frame_count - 1}."
        )
    if isinstance(dpi, bool) or not isinstance(dpi, int) or dpi <= 0:
        raise ValueError("dpi must be a positive integer.")

    output = Path(output_directory).expanduser().resolve()
    output.mkdir(parents=True, exist_ok=True)
    panel_paths = tuple(output / name for name in _PANEL_FILENAMES)
    overview_path = output / "00_method_overview.png"
    frame_number = int(run.sequence.frames[frame_index].frame_number)

    diagnostics = recompute_evidence_diagnostics(run)
    base_excess_z = diagnostics.base_excess_z
    running_difference_z = diagnostics.running_difference_z
    leading_edge_z = diagnostics.leading_edge_z
    assert base_excess_z is not None
    assert running_difference_z is not None
    assert leading_edge_z is not None

    loaded = run.sequence.read_frame(frame_index)
    original = np.asarray(loaded.data, dtype=np.float32)
    polar = remap_image_to_polar(original, run.polar_grid)
    low, high, linear_width = _sequence_display_limits(run)
    display_maximum = float(np.arcsinh((high - low) / linear_width))
    original_display = _asinh_display(
        original,
        low=low,
        linear_width=linear_width,
    )
    polar_display = _asinh_display(
        polar,
        low=low,
        linear_width=linear_width,
    )
    background_display = _asinh_display(
        diagnostics.temporal_background,
        low=low,
        linear_width=linear_width,
    )

    pyplot = _pyplot()

    # 01 — original image, with an explicitly presentation-only stretch.
    figure, axis = pyplot.subplots(figsize=(8.5, 7.2))
    artist = axis.imshow(
        original_display,
        origin="lower",
        cmap="gray",
        vmin=0.0,
        vmax=display_maximum,
    )
    axis.set_title(
        "01  Original input — display-only asinh stretch",
        fontweight="bold",
    )
    axis.set_xlabel("Image x (pixel)")
    axis.set_ylabel("Image y (pixel)")
    figure.colorbar(artist, ax=axis, pad=0.02).set_label(
        "asinh-scaled display value (not used by tracker)"
    )
    geometry = run.sequence.geometry
    sampling_radius = (
        run.configuration.polar.minimum_radius_rsun * geometry.solar_radius_px
    )
    circle = pyplot.Circle(
        (geometry.center_x_px, geometry.center_y_px),
        sampling_radius,
        fill=False,
        color="#ffcc33",
        linestyle="--",
        linewidth=1.2,
        label=(
            "polar tracking begins at "
            rf"{run.configuration.polar.minimum_radius_rsun:g} $R_\odot$"
        ),
    )
    axis.add_patch(circle)
    vector_length = 0.55 * geometry.solar_radius_px
    for label, vector, color in (
        ("N", geometry.north_vector_yx, "#00e5ff"),
        ("E", geometry.east_vector_yx, "#ff7f0e"),
    ):
        vector_y, vector_x = vector
        axis.annotate(
            label,
            xy=(
                geometry.center_x_px + vector_length * vector_x,
                geometry.center_y_px + vector_length * vector_y,
            ),
            xytext=(geometry.center_x_px, geometry.center_y_px),
            color=color,
            fontweight="bold",
            arrowprops={"arrowstyle": "->", "color": color, "linewidth": 1.5},
        )
    axis.legend(loc="lower left", framealpha=0.85, fontsize="small")
    _add_caption(
        figure,
        "The FITS pixel values enter the science pipeline unchanged; the asinh "
        "stretch exists only to reveal faint structure. This historical "
        "synthetic-bypass input has not received Level 2 PSF deconvolution or "
        "Level 3 geometric correction.",
    )
    figure.tight_layout(rect=(0.0, 0.07, 1.0, 1.0))
    _save_figure(
        pyplot,
        figure,
        panel_paths[0],
        dpi=dpi,
        title="01 Original input",
    )

    # 02 — Cartesian-to-polar science coordinate transform.
    figure, axis = pyplot.subplots(figsize=(10.2, 6.5))
    _render_polar_image(
        axis,
        run,
        polar_display,
        cmap="gray",
        vmin=0.0,
        vmax=display_maximum,
        colorbar_label="asinh-scaled display value (display only)",
        figure=figure,
    )
    axis.set_title(
        "02  Polar remap — science coordinate transform; display-only stretch",
        fontweight="bold",
    )
    _add_caption(
        figure,
        "Each image is interpolated onto position angle × projected radius. "
        "NaN regions preserve the rectangular detector boundary.",
    )
    figure.tight_layout(rect=(0.0, 0.07, 1.0, 1.0))
    _save_figure(
        pyplot,
        figure,
        panel_paths[1],
        dpi=dpi,
        title="02 Polar remap",
    )

    # 03 — robust temporal background in polar science space.
    percentile = run.configuration.evidence.temporal_background_percentile
    figure, axis = pyplot.subplots(figsize=(10.2, 6.5))
    _render_polar_image(
        axis,
        run,
        background_display,
        cmap="gray",
        vmin=0.0,
        vmax=display_maximum,
        colorbar_label="asinh-scaled display value (display only)",
        figure=figure,
    )
    axis.set_title(
        f"03  Full-window/noncausal temporal background — science "
        f"{percentile:g}th percentile; display-only stretch",
        fontweight="bold",
    )
    _add_caption(
        figure,
        f"The percentile is taken through all {run.sequence.frame_count} smoothed "
        "polar frames at each position-angle/radius cell. It uses future context; "
        "only its rendering is stretched.",
    )
    figure.tight_layout(rect=(0.0, 0.07, 1.0, 1.0))
    _save_figure(
        pyplot,
        figure,
        panel_paths[2],
        dpi=dpi,
        title="03 Temporal background",
    )

    # 04–06 — signed, robustly normalized science evidence channels.
    previous_frame_label = (
        str(run.sequence.frames[frame_index - 1].frame_number)
        if frame_index > 0
        else "no predecessor"
    )
    evidence_panels = (
        (
            base_excess_z[frame_index],
            "04  Base-excess evidence — science robust z-score",
            "Current smoothed polar intensity minus the temporal background, "
            "then robustly normalized independently at each radius.",
            panel_paths[3],
        ),
        (
            running_difference_z[frame_index],
            "05  Running-difference evidence — frame "
            f"{previous_frame_label}→"
            f"{frame_number}; science robust z-score",
            "Current smoothed polar intensity minus the preceding frame, with "
            "no division by elapsed time; the first frame is defined as zero.",
            panel_paths[4],
        ),
        (
            leading_edge_z[frame_index],
            "06  Leading-edge evidence — science outward-edge z-score",
            "The negative radial derivative of base excess makes the outer "
            "edge of a bright front positive, then radius-wise normalization "
            "puts it on the common evidence scale.",
            panel_paths[5],
        ),
    )
    for values, title, caption, path in evidence_panels:
        figure, axis = pyplot.subplots(figsize=(10.2, 6.5))
        signed_limit = run.configuration.evidence.z_score_clip
        _render_polar_image(
            axis,
            run,
            values,
            cmap="coolwarm",
            vmin=-signed_limit,
            vmax=signed_limit,
            colorbar_label="robust z-score (science value)",
            figure=figure,
        )
        axis.set_title(title, fontweight="bold")
        _add_caption(figure, caption)
        figure.tight_layout(rect=(0.0, 0.07, 1.0, 1.0))
        _save_figure(
            pyplot,
            figure,
            path,
            dpi=dpi,
            title=title,
        )

    # 07 — science-weighted score.
    frame_score = run.likelihood.score[frame_index]
    score_maximum = float(run.configuration.evidence.z_score_clip)
    figure, axis = pyplot.subplots(figsize=(10.2, 6.5))
    _render_polar_image(
        axis,
        run,
        frame_score,
        cmap="magma",
        vmin=0.0,
        vmax=score_maximum,
        colorbar_label="combined evidence score (science value)",
        figure=figure,
    )
    axis.contour(
        run.polar_grid.radius_rsun,
        run.polar_grid.position_angle_deg,
        frame_score,
        levels=[run.configuration.tracking.score_threshold],
        colors=["#00e5ff"],
        linewidths=0.7,
    )
    axis.set_title(
        "07  Combined front score — weighted positive science evidence",
        fontweight="bold",
    )
    _add_caption(
        figure,
        "Positive base excess, running difference, and leading-edge evidence "
        "are clipped and weighted; cells below the leading-edge gate are zeroed. "
        f"The cyan contour marks the candidate threshold "
        f"{run.configuration.tracking.score_threshold:g}.",
    )
    figure.tight_layout(rect=(0.0, 0.07, 1.0, 1.0))
    _save_figure(
        pyplot,
        figure,
        panel_paths[6],
        dpi=dpi,
        title="07 Combined front score",
    )

    # 08 — local score candidates versus samples retained by global tracking.
    candidate_angles, candidate_radii = _frame_candidates_for_all_angles(
        run,
        frame_index,
    )
    retained = run.front.observed_mask[frame_index]
    figure, axis = pyplot.subplots(figsize=(10.2, 6.5))
    _render_polar_image(
        axis,
        run,
        frame_score,
        cmap="magma",
        vmin=0.0,
        vmax=score_maximum,
        colorbar_label="combined evidence score (science value)",
        figure=figure,
    )
    if candidate_radii.size:
        axis.scatter(
            candidate_radii,
            candidate_angles,
            s=16,
            facecolors="none",
            edgecolors="#ffcc33",
            linewidths=0.8,
            label="Local candidates",
        )
    if np.any(retained):
        axis.scatter(
            run.front.radius_rsun[frame_index, retained],
            run.front.position_angle_deg[retained],
            s=22,
            color="#00e5ff",
            edgecolors="black",
            linewidths=0.35,
            label="Retained tracker support",
        )
    axis.set_title(
        "08  Local candidates vs temporally/angularly retained tracker support",
        fontweight="bold",
    )
    handles, labels = axis.get_legend_handles_labels()
    if handles:
        axis.legend(handles, labels, loc="best", framealpha=0.85)
    _add_caption(
        figure,
        "Candidate peaks pass the per-frame score threshold. The sparse path "
        "and circular angular-component tests retain the strongest outward "
        "support component; it is not a truth contour.",
    )
    figure.tight_layout(rect=(0.0, 0.07, 1.0, 1.0))
    _save_figure(
        pyplot,
        figure,
        panel_paths[7],
        dpi=dpi,
        title="08 Candidate and retained front comparison",
    )

    # 09 — one representative sparse path through the full time-radius score.
    angle_index = _representative_angle_index(run, frame_index)
    representative_angle = float(
        run.polar_grid.position_angle_deg[angle_index]
    )
    candidate_time, candidate_radius = _time_radius_candidates(run, angle_index)
    elapsed = np.asarray(run.sequence.elapsed_seconds, dtype=np.float64)
    figure, axis = pyplot.subplots(figsize=(10.4, 6.6))
    artist = axis.pcolormesh(
        elapsed,
        run.polar_grid.radius_rsun,
        run.likelihood.score[:, angle_index, :].T,
        shading="nearest",
        cmap="magma",
        vmin=0.0,
        vmax=_positive_display_limit(
            run.likelihood.score[:, angle_index, :],
            floor=run.configuration.tracking.score_threshold,
        ),
    )
    figure.colorbar(artist, ax=axis, pad=0.02).set_label(
        "combined evidence score (science value)"
    )
    if candidate_time.size:
        axis.scatter(
            candidate_time,
            candidate_radius,
            s=22,
            facecolors="none",
            edgecolors="#ffcc33",
            linewidths=0.9,
            label="Local candidates",
        )
    selected_radius = run.front.radius_rsun[:, angle_index]
    selected = np.isfinite(selected_radius)
    if np.any(selected):
        axis.plot(
            elapsed,
            selected_radius,
            color="#00e5ff",
            marker="o",
            markersize=3.5,
            linewidth=1.7,
            label="Retained outward tracker path",
        )
    axis.axvline(
        elapsed[frame_index],
        color="white",
        linestyle="--",
        linewidth=1.0,
        label="Example timestep",
    )
    axis.set_xlabel("Elapsed time (s)")
    axis.set_ylabel(r"Projected radius ($R_\odot$)")
    axis.set_title(
        "09  Representative time–radius sparse path "
        f"at position angle {representative_angle:g}°",
        fontweight="bold",
    )
    handles, labels = axis.get_legend_handles_labels()
    if handles:
        axis.legend(handles, labels, loc="best", framealpha=0.85)
    _add_caption(
        figure,
        "Tracking links score peaks outward through nominal frame intervals, "
        "allows configured short gaps, and penalizes large radial jumps.",
    )
    figure.tight_layout(rect=(0.0, 0.07, 1.0, 1.0))
    _save_figure(
        pyplot,
        figure,
        panel_paths[8],
        dpi=dpi,
        title="09 Representative time-radius path",
    )

    # 10 — selected polar samples projected back into detector coordinates.
    front_x, front_y = _backproject_front(run, frame_index)
    figure, axis = pyplot.subplots(figsize=(8.5, 7.2))
    artist = axis.imshow(
        original_display,
        origin="lower",
        cmap="gray",
        vmin=0.0,
        vmax=display_maximum,
    )
    figure.colorbar(artist, ax=axis, pad=0.02).set_label(
        "asinh-scaled display value (background only)"
    )
    if front_x.size:
        axis.scatter(
            front_x,
            front_y,
            s=25,
            color="#00e5ff",
            edgecolors="black",
            linewidths=0.35,
            label="Backprojected retained tracker support",
        )
        axis.legend(loc="best", framealpha=0.85)
    axis.set_xlabel("Image x (pixel)")
    axis.set_ylabel("Image y (pixel)")
    axis.set_title(
        "10  Retained polar tracker support backprojected onto input — "
        "display-only background stretch",
        fontweight="bold",
    )
    _add_caption(
        figure,
        "Cyan points are selected science coordinates mapped through the stored "
        "solar north/east vectors; they are provisional tracker support, not a "
        "truth contour. The grayscale asinh stretch is display-only.",
    )
    figure.tight_layout(rect=(0.0, 0.07, 1.0, 1.0))
    _save_figure(
        pyplot,
        figure,
        panel_paths[9],
        dpi=dpi,
        title="10 Backprojected retained front",
    )

    # 11 — angular front samples reduced to the configured headline percentile.
    height_percentile = run.configuration.summary.height_percentile
    frame_radii = run.front.radius_rsun[frame_index, retained]
    frame_angles = run.front.position_angle_deg[retained]
    headline_height = float(run.summary.height_rsun[frame_index])
    figure, (angle_axis, percentile_axis) = pyplot.subplots(
        1,
        2,
        figsize=(12.2, 5.8),
    )
    if frame_radii.size:
        angle_axis.scatter(
            frame_angles,
            frame_radii,
            s=28,
            color="#00a9bd",
            label="Retained angular samples",
            zorder=3,
        )
        above_headline = frame_radii >= headline_height
        angle_axis.scatter(
            frame_angles[above_headline],
            frame_radii[above_headline],
            s=52,
            facecolors="none",
            edgecolors="#d62728",
            linewidths=1.3,
            label=f"Samples at/above {height_percentile:g}th percentile",
            zorder=4,
        )
        sorted_radii = np.sort(frame_radii)
        percentile_rank = (
            np.arange(sorted_radii.size, dtype=np.float64)
            / max(sorted_radii.size - 1, 1)
            * 100.0
        )
        percentile_axis.plot(
            percentile_rank,
            sorted_radii,
            color="#00a9bd",
            marker="o",
            markersize=3.5,
        )
    else:
        angle_axis.text(
            0.5,
            0.5,
            "No retained samples at this timestep",
            transform=angle_axis.transAxes,
            ha="center",
            va="center",
        )
        percentile_axis.text(
            0.5,
            0.5,
            "Scalar height unavailable",
            transform=percentile_axis.transAxes,
            ha="center",
            va="center",
        )
    if math.isfinite(headline_height):
        for axis in (angle_axis, percentile_axis):
            axis.axhline(
                headline_height,
                color="#d62728",
                linestyle="--",
                linewidth=1.5,
                label=f"{height_percentile:g}th percentile = "
                rf"{headline_height:.3f} $R_\odot$",
            )
        percentile_axis.axvline(
            height_percentile,
            color="#d62728",
            linestyle=":",
            linewidth=1.2,
        )
    angle_axis.set_xlabel("Solar position angle (deg)")
    angle_axis.set_ylabel(r"Retained radius ($R_\odot$)")
    angle_axis.set_title("Angularly resolved retained tracker support")
    percentile_axis.set_xlabel("Sample percentile")
    percentile_axis.set_ylabel(r"Retained radius ($R_\odot$)")
    percentile_axis.set_title("Sorted radii and scalar reduction")
    for axis in (angle_axis, percentile_axis):
        handles, labels = axis.get_legend_handles_labels()
        if handles:
            axis.legend(handles, labels, loc="best", fontsize="small")
        axis.grid(alpha=0.22)
    finite_radii = frame_radii[np.isfinite(frame_radii)]
    maximum_radius = float(np.max(finite_radii)) if finite_radii.size else math.nan
    if finite_radii.size:
        maximum_local_index = int(np.nanargmax(frame_radii))
        maximum_angle = float(frame_angles[maximum_local_index])
    else:
        maximum_angle = math.nan
    statistics = (
        f"observed angles: {frame_radii.size}\n"
        f"coverage: {run.summary.coverage_fraction[frame_index]:.4f}\n"
        rf"headline: {headline_height:.5f} $R_\odot$" "\n"
        rf"maximum: {maximum_radius:.5f} $R_\odot$ at PA {maximum_angle:g}°" "\n"
        f"circular PA center: {run.summary.position_angle_deg[frame_index]:.2f}°\n"
        f"sampled angular width: {run.summary.angular_width_deg[frame_index]:.0f}°"
    )
    percentile_axis.text(
        0.03,
        0.97,
        statistics,
        transform=percentile_axis.transAxes,
        ha="left",
        va="top",
        fontsize=9,
        bbox={"facecolor": "white", "edgecolor": "0.75", "alpha": 0.88},
    )
    figure.suptitle(
        f"11  Science reduction to configured {height_percentile:g}th-percentile "
        "scalar height",
        fontweight="bold",
    )
    _add_caption(
        figure,
        "This is the spatial percentile across accepted angular radii at this "
        "frame—not a temporal percentile, confidence interval, maximum, or "
        "fitted global contour.",
    )
    figure.tight_layout(rect=(0.0, 0.08, 1.0, 0.94))
    _save_figure(
        pyplot,
        figure,
        panel_paths[10],
        dpi=dpi,
        title="11 Scalar headline-height reduction",
    )

    _write_contact_sheet(
        pyplot,
        panel_paths,
        overview_path,
        frame_index=frame_index,
        frame_number=frame_number,
        dpi=dpi,
    )
    return CMEExplanationArtifacts(
        frame_index=frame_index,
        frame_number=frame_number,
        representative_position_angle_deg=representative_angle,
        panel_paths=panel_paths,
        overview_path=overview_path,
    )


__all__ = [
    "CMEExplanationArtifacts",
    "recompute_evidence_diagnostics",
    "write_cme_method_explanation",
]
